# Generated by Django 4.2.3 on 2023-07-18 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce_Ship_from_farm',
            fields=[
                ('shipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=9)),
                ('driver_phone', models.CharField(max_length=13)),
                ('shipping_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('total_product_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_from_farm_created_by', to=settings.AUTH_USER_MODEL)),
                ('produce', models.ForeignKey(db_column='produce_id', on_delete=django.db.models.deletion.RESTRICT, related_name='repackaged_produce_produce', to='cms.produce')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_from_farm_transporter', to='users.transporter')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.RESTRICT, related_name='repackaged_produce_unit', to='cms.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_from_farm_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipping_from_farm',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shipping_from_farm',
            name='transporter',
        ),
        migrations.RemoveField(
            model_name='shipping_from_farm',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='repackaged_produce_to_services',
            name='repackaged_produce',
        ),
        migrations.AlterField(
            model_name='repackaged_produce_to_services',
            name='product_service',
            field=models.ForeignKey(blank=True, db_column='service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.product_services'),
        ),
        migrations.DeleteModel(
            name='Repackaged_produce',
        ),
        migrations.DeleteModel(
            name='Shipping_from_farm',
        ),
        migrations.AddField(
            model_name='repackaged_produce_to_services',
            name='shipped_produce',
            field=models.ForeignKey(blank=True, db_column='shipment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.produce_ship_from_farm'),
        ),
        migrations.AddIndex(
            model_name='produce_ship_from_farm',
            index=models.Index(fields=['driver_phone', 'shipping_date'], name='cms_produce_driver__89cff5_idx'),
        ),
    ]
