# Generated by Django 4.2.3 on 2023-07-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cms', '0004_rename_total_product_cost_produce_ship_from_farm_total_produce_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce_ship_from_farm',
            name='buyer',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_from_farm_buyer', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='produce_ship_from_farm',
            name='produce',
            field=models.ForeignKey(db_column='produce_id', on_delete=django.db.models.deletion.RESTRICT, related_name='shipping_from_farm_produce', to='cms.produce'),
        ),
        migrations.AlterField(
            model_name='produce_ship_from_farm',
            name='unit',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.RESTRICT, related_name='shipping_from_farm_unit', to='cms.unit'),
        ),
    ]
