# Generated by Django 4.2.3 on 2023-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_produce_ship_from_farm_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening_closing_stock',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produce_ship_from_farm',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='received_products',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returned_produce',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
