# Generated by Django 4.2.3 on 2023-07-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cms', '0006_opening_closing_stock_is_deleted_order_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='received_products',
            name='received_by',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_products_received_by', to='users.employee'),
        ),
    ]
