# Generated by Django 4.2.3 on 2023-07-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cms', '0007_received_products_received_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='received_products',
            old_name='unit_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='received_products',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_products_transporter', to='users.transporter'),
        ),
    ]
