# Generated by Django 4.2.3 on 2023-07-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_rename_unit_quantity_received_products_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='received_products',
            old_name='received_products',
            new_name='received_product_id',
        ),
    ]
