version: '3.9'


services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ghala

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend: 
    build: 
      context: ./ghala
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./ghala:/app/ghala

    depends_on:
      - postgres

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4
      restart: always
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: mutwirifranco@gmail.com
        PGADMIN_DEFAULT_PASSWORD: admin
      volumes:
        - ./pgadmin-data:/var/lib/pgadmin
      depends_on:
        - postgres