# Generated by Django 4.2.3 on 2023-07-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_employee_location_remove_farmer_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_add_farmers', 'Can add farmers'), ('can_add_vendors', 'Can add Vendors'), ('can_list_farmers', 'Can list farmers'), ('can_list_vendors', 'Can list vendors'), ('can_list_orders', 'Can list orders'))},
        ),
    ]
