# Generated by Django 4.2.3 on 2023-07-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_rehired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('sales_person', 'sales person'), ('produce_buyer', 'producebuyer')], null=True),
        ),
    ]
