# Generated by Django 4.2.3 on 2023-07-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_employee_is_rehired_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
