# Generated by Django 4.2.3 on 2023-07-15 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce_buyer_to_farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(blank=True, default=datetime.date(2099, 12, 31), null=True)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Produce_buyer_to_farmer', to='users.farmer')),
                ('produce_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Produce_buyer_to_farmer', to='users.employee')),
            ],
        ),
    ]
