# Generated by Django 4.2.3 on 2023-07-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_produce_buyer_to_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('sales_person', 'sales person'), ('produce_buyer', 'produce buyer')], null=True),
        ),
    ]
